#!/usr/bin/env python

import sys
from app import M16CFlash

if __name__ == "__main__":

	if str(sys.version).split()[0].split('.') < ['2', '4', '0']:
		print('Warning: This program requires python >= 2.4 to work properly.')

	try:
		flash = M16CFlash()
		flash.run()
	except Exception, (error):
		sys.exit(error)
