#!/usr/bin/env python

#
#    Simple Flasher is a serial line flashing application for Renesas M16C
#    16-bit single-chip microcomputer.
#
#    Copyright (C) 2007  Simon Aittamaa <simait-2@student.ltu.se>.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
from m16c import M16CFlashApp

if __name__ == "__main__":

	if str(sys.version).split()[0].split('.') < ['2', '4', '0']:
		print('Warning: This program requires python >= 2.4 to work properly.')

	try:
		flash = M16CFlashApp()
		flash.run()
	except Exception, (error):
		sys.exit(error)
